# Generated by Django 3.2.18 on 2023-04-07 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import sorl.thumbnail.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Users's profile",
                "verbose_name_plural": "Users' profiles",
            },
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="birthday",
            field=models.DateField(
                blank=True, null=True, verbose_name="Birthday"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="coffee_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Question about coffee"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                verbose_name="Profile photo",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_login_attempt",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last attempt to log in"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
