# Generated by Django 3.2.18 on 2023-04-06 15:00

import django.db.models.deletion
from django.db import migrations, models

import feedback.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="текст сообщения")),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Получено"),
                            ("processing", "В обработке"),
                            ("replied", "Ответ дан"),
                        ],
                        default="received",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="адрес электронной почты"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=feedback.models.feedback_files_path,
                        verbose_name="файл",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="feedback.feedback",
                        verbose_name="обратная связь",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feedback",
            name="personal_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="feedback.personalinfo",
                verbose_name="персональная информация",
            ),
        ),
    ]
