# Generated by Django 3.2.18 on 2023-04-06 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name": "обратная связь"},
        ),
        migrations.AlterModelOptions(
            name="file",
            options={"verbose_name": "файл", "verbose_name_plural": "файлы"},
        ),
        migrations.AlterModelOptions(
            name="personalinfo",
            options={"verbose_name": "личная информация"},
        ),
    ]
