# Generated by Django 3.2.18 on 2023-04-12 08:16

import django.db.models.deletion
from django.db import migrations, models

import feedback.models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_auto_20230406_1722"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name": "feedback"},
        ),
        migrations.AlterModelOptions(
            name="file",
            options={"verbose_name": "file", "verbose_name_plural": "files"},
        ),
        migrations.AlterModelOptions(
            name="personalinfo",
            options={"verbose_name": "personal information"},
        ),
        migrations.AlterField(
            model_name="feedback",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="creation time"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="personal_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="feedback.personalinfo",
                verbose_name="personal information",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "received"),
                    ("processing", "processing"),
                    ("replied", "replied"),
                ],
                default="received",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="text",
            field=models.TextField(verbose_name="messsage text"),
        ),
        migrations.AlterField(
            model_name="file",
            name="feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="feedback.feedback",
                verbose_name="feedback",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                upload_to=feedback.models.feedback_files_path,
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
    ]
