# Generated by Django 3.2.18 on 2023-04-17 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20230407_1921"),
        ("tasks", "0002_auto_20230416_0319"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "task", "verbose_name_plural": "tasks"},
        ),
        migrations.AlterField(
            model_name="task",
            name="break_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="current break ends"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="break_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="next break starts"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="breaks_duration",
            field=models.DurationField(
                blank=True, null=True, verbose_name="breaks duration"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="duration",
            field=models.DurationField(verbose_name="duration"),
        ),
        migrations.AlterField(
            model_name="task",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="ending time"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(
                default=False, verbose_name="is task completed"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_running",
            field=models.BooleanField(
                default=False, verbose_name="is task running"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_with_breaks",
            field=models.BooleanField(
                default=False, verbose_name="is with breaks?"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=150, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.DateTimeField(verbose_name="start time"),
        ),
        migrations.AlterField(
            model_name="task",
            name="time_between_breaks",
            field=models.DurationField(
                blank=True, null=True, verbose_name="time between breaks"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
                verbose_name="user",
            ),
        ),
    ]
