# Generated by Django 3.2.18 on 2023-04-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_auto_20230417_1910"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ("start_time",),
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        ),
        migrations.RemoveField(
            model_name="task",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="task",
            name="is_running",
        ),
        migrations.AddField(
            model_name="task",
            name="pause_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="task suspension time"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="sleep_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="sleep start time"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="state",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (
                        0,
                        "the task has not been suspended yet or the error has already been taken into account",
                    ),
                    (1, "the task was suspended during the first sleep"),
                    (2, "the task was suspended during the second sleep"),
                    (3, "the task was suspended during the third sleep"),
                ],
                default=0,
                verbose_name="where was the task suspended",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "running"),
                    ("break", "break"),
                    ("completed", "completed"),
                    ("paused", "paused"),
                ],
                default="running",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="celery-task's id",
            ),
        ),
    ]
